DROP TABLE IF EXISTS ORDER_LINE;
DROP TABLE IF EXISTS SALES_ORDER;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE CUSTOMER (
  CUSTOMER_ID VARCHAR(16) NOT NULL,
  NAME VARCHAR(32) NOT NULL,
  ADDRESS VARCHAR(64),
  PHONE1 VARCHAR(16),
  PHONE2 VARCHAR(16),
  CREDIT_LIMIT INT(16) NOT NULL,
  CREDIT FLOAT(16) NOT NULL,
  PRIMARY KEY (CUSTOMER_ID)
) ENGINE=INNODB;

CREATE TABLE PRODUCT (
  PRODUCT_ID VARCHAR(16) NOT NULL,
  DESCRIPTION VARCHAR(1024) NOT NULL,
  PRICE FLOAT(16) NOT NULL,
  QUANTITY INT(16) NOT NULL,
  PRIMARY KEY (PRODUCT_ID)
) ENGINE=INNODB;

CREATE TABLE SALES_ORDER (
  ORDER_NUMBER VARCHAR(16) NOT NULL,
  CUSTOMER_ID VARCHAR(16) NOT NULL,
  TOTAL_PRICE FLOAT(16) NOT NULL,
  PRIMARY KEY (ORDER_NUMBER),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE ORDER_LINE(
  ID INT(16) NOT NULL AUTO_INCREMENT,
  ORDER_ID VARCHAR(16) NOT NULL,
  PRODUCT_ID VARCHAR(16) NOT NULL,
  QUANTITY INT(16) NOT NULL,
  FOREIGN KEY (ORDER_ID) REFERENCES SALES_ORDER(ORDER_NUMBER) ON DELETE CASCADE,
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE,
  PRIMARY KEY (ID),
  CONSTRAINT U_ORDERID_PRODUCTID UNIQUE (ORDER_ID,PRODUCT_ID)
) ENGINE=INNODB;

SHOW TABLES;