DROP TABLE IF EXISTS ORDER_LINE;
DROP TABLE IF EXISTS SALES_ORDER;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE CUSTOMER (
  CUSTOMER_ID VARCHAR(10) NOT NULL,
  NAME VARCHAR(20) NOT NULL,
  ADDRESS VARCHAR(20),
  PHONE1 VARCHAR(20),
  PHONE2 VARCHAR(20),
  CREDIT_LIMIT INT(10) NOT NULL,
  CREDIT INT(10) NOT NULL,
  PRIMARY KEY (CUSTOMER_ID)
) ENGINE=INNODB;

CREATE TABLE PRODUCT (
  PRODUCT_ID VARCHAR(10) NOT NULL,
  DESCRIPTION VARCHAR(1024) NOT NULL,
  PRICE FLOAT(20) NOT NULL,
  QUANTITY INT(20) NOT NULL,
  PRIMARY KEY (PRODUCT_ID)
) ENGINE=INNODB;

CREATE TABLE SALES_ORDER (
  ORDER_NUMBER VARCHAR(20) NOT NULL,
  CUSTOMER_ID VARCHAR(10) NOT NULL,
  TOTAL_PRICE FLOAT(32) NOT NULL,
  PRIMARY KEY (ORDER_NUMBER),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE ORDER_LINE(
  ORDER_ID VARCHAR(20) NOT NULL,
  PRODUCT_ID VARCHAR(10) NOT NULL,
  QUANTITY INT(20) NOT NULL,
  FOREIGN KEY (ORDER_ID) REFERENCES SALES_ORDER(ORDER_NUMBER) ON DELETE CASCADE,
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE,
  PRIMARY KEY (ORDER_ID, PRODUCT_ID)
) ENGINE=INNODB;

SHOW TABLES;